### ISSUE TITLE
about DAX Function

### ISSUE THREAD

**Issue by jrani1006** [MicrosoftDocs/powerbi-docs.ko-kr#10]
In the formular, '고유' request change to 'Distinct' 
국가=Distinct('지리'[국가])

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 49462b9d-81da-e29a-f148-1fd95395a570
* Version Independent ID: 4ce1f7c2-0170-35b5-adca-c92c41fb7fc1
* Content: [모델링 | Microsoft Power BI - Power BI](https://docs.microsoft.com/ko-kr/power-bi/guided-learning/modeling?tutorial-step=8)
* Content Source: [powerbi-docs/guided-learning/modeling.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr.ko-KR/blob/live-sxs/powerbi-docs/guided-learning/modeling.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LisandroSu** [comment]
안녕하세요. @jrani1006  님,

댓글을 남겨 주셔서 감사드리며 Microsoft는 docs.microsoft.com의 환경을 개선하기 위해 노력하고 있습니다. 그러나 귀하의 의견을 처리하기 위해서는 추가 정보가 필요합니다. 자세한 정보를 제공하고 댓글에 대해 명확하게 설명해 주실 수 있으신지요?

감사합니다.
Microsoft DOCS International 팀

**Comment by jrani1006** [comment]
안녕하세요.

물론 추가 정보를  입력하는 부분은 가능합니다.

자세한 정보를 제공해야 한다는건 댓글에 상세한 설명이 필요한건가요?

서주란 드림


________________________________
보낸 사람: Lisandro <notifications@github.com>
보낸 날짜: 2018년 11월 2일 금요일 오후 7:19
받는 사람: MicrosoftDocs/powerbi-docs.ko-kr
참조: Juran; Mention
제목: Re: [MicrosoftDocs/powerbi-docs.ko-kr] about DAX Function (#10)


안녕하세요. @jrani1006<https://github.com/jrani1006> 님,

댓글을 남겨 주셔서 감사드리며 Microsoft는 docs.microsoft.com의 환경을 개선하기 위해 노력하고 있습니다. 그러나 귀하의 의견을 처리하기 위해서는 추가 정보가 필요합니다. 자세한 정보를 제공하고 댓글에 대해 명확하게 설명해 주실 수 있으신지요?

감사합니다.
Microsoft DOCS International 팀

**Comment by CeciAc** [comment]
안녕하세요. @jrani1006 님,
이전 댓글에 대한 후속 작업을 진행하고 있습니다. 귀하의 의견을 처리하기 위해서는 추가 정보가 필요합니다. 자세한 정보를 제공하고 댓글에 대해 명확하게 설명해 주실 수 있으신지요?
감사합니다.
Microsoft DOCS International 팀

**Comment by CeciAc** [comment]
안녕하세요. @jrani1006  님,
댓글을 남겨 주셔서 다시 한번 감사합니다.
죄송하지만, 여전히 누락된 정보가 있어 귀하의 의견을 처리할 수 없습니다. 지금은 이 GitHub 문제를 종결하지만, 향후 더 많은 의견을 제출해 주시면 감사하겠습니다.
감사합니다.
Microsoft DOCS International 팀
