### ISSUE TITLE
번역 오류

### ISSUE THREAD

**Issue by wonhyukc** [MicrosoftDocs/powerbi-docs.ko-kr#207]
절차3의 

#데이터 집합
은 
#dataset 
을 과도하게 번역하여 코드가 동작하지 않습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 000c7cf3-dbf4-92c6-3eb6-837329704cfa
* Version Independent ID: 81aa68ff-30b2-84e1-0f15-020890569527
* Content: [R을 사용하여 Power BI 시각적 개체 만들기 - Power BI](https://docs.microsoft.com/ko-kr/power-bi/desktop-r-visuals#feedback)
* Content Source: [powerbi-docs/desktop-r-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs.ko-kr/blob/live/powerbi-docs/desktop-r-visuals.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
안녕하세요. , @wonhyukc 
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요, @wonhyukc 님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/power-bi/desktop-r-visuals#feedback 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
