### ISSUE TITLE
Images not displayed

### ISSUE THREAD

**Issue by v-radelg** [MicrosoftDocs/powerbi-docs.ko-kr#22]
https://docs.microsoft.com/en-us/power-bi/service-share-dashboards

![image](https://user-images.githubusercontent.com/16900799/49758810-a77fc100-fc9e-11e8-842e-73ceb3f248f0.png)

https://docs.microsoft.com/ko-kr/power-bi/service-share-dashboards

![image](https://user-images.githubusercontent.com/16900799/49758844-b8c8cd80-fc9e-11e8-9484-13f09d00877d.png)

**Comment by CeciAc** [comment]
Hello, @v-radelg 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @v-radelg

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages XXX. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
