### ISSUE TITLE
Need update!

### ISSUE THREAD

**Issue by hongju** [MicrosoftDocs/powerbi-docs.ko-kr#269]
There is different from English page. I can't find information for viewer role in this page.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [새 작업 영역-Power BI에서에서 작업 구성 - Power BI](https://docs.microsoft.com/ko-kr/power-bi/service-new-workspaces)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs.ko-kr/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by CeciAc** [comment]
Hello, @hongju

Thank you for your feedback and suggestion.  
The file is currently under localization process. We will release this article soon.

Many thanks for your support. 
Kind regards,

Microsoft DOCS International Team
